title: SAMP Tools
description: Документация по инструментам для SAMP

# Отключаем тему
theme: null

# Настройки сайта
url: "https://amfeeque.github.io"
baseurl: "/samp.tools"

# Обработка markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

# Настройки сборки
timezone: Europe/Moscow
encoding: utf-8

# Отключаем ненужные плагины
plugins: []

# Отключаем автоматическое создание постов
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Основная конфигурация
baseurl: "/samp.tools"
url: "https://amfeeque.github.io"

# Настройки сайта
title: "SAMP Tools"
description: "Документация по инструментам для SAMP"

# Настройки обработки
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Пути
collections_dir: .

# Исключаем ненужные файлы
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .github
  - .git
  - .gitignore
  - .github
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - _site
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .DS_Store
  - Thumbs.db
