title: SAMP Tools
description: Документация по инструментам для SAMP

# Отключаем тему
theme: null

# Настройки сайта
url: "https://amfeeque.github.io"
baseurl: "/samp.tools"

# Обработка markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge

# Настройки сборки
timezone: Europe/Moscow
encoding: utf-8

# Отключаем ненужные плагины
plugins: []

# Отключаем автоматическое создание постов
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Исключаем ненужные файлы
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - .github
  - pages
