title: SAMP Tools
description: Документация по инструментам для SAMP

theme: minima

# Настройки сайта
url: "https://amfeeque.github.io"
baseurl: "/samp.tools"

# Навигация
header_pages:
  - index.md
  - AdminTools.md
  - Tracers.md
  - SampDB.md

# Обработка markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Настройки сборки
timezone: Europe/Moscow
encoding: utf-8

# Плагины
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
